# Usar una imagen base de Node.js
FROM node:18

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Instalar ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Exponer el puerto que el contenedor utilizará
EXPOSE 8080

# Comando para iniciar tu bot
CMD ["node", "Discord.js"]
