# Usar la imagen base de Node.js
FROM node:18

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Instalar ffmpeg y asegurarse de que esté en el PATH global
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    ln -s /usr/bin/ffmpeg /usr/local/bin/ffmpeg

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Establecer la variable de entorno FFMPEG_PATH para DisTube
ENV FFMPEG_PATH="/usr/local/bin/ffmpeg"

# Exponer el puerto que el contenedor utilizará
EXPOSE 8080

# Comando para iniciar tu bot
CMD ["node", "Discord.js"]
